version: '3'
services:
  theatre-db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
  redis:  
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  elasticsearch:
    image: elasticsearch:8.17.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - es_volume:/usr/share/elasticsearch/data
volumes:
  es_volume: