version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.17.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - es_volume:/usr/share/elasticsearch/data
volumes:
  es_volume: